"use client";

import Link from "next/link";
import { AlertTriangle, Bell, CheckCircle, FileText, Check } from "lucide-react";
import { useState } from "react";
import { PageHeader } from "@/components/shared/PageHeader";
import { markAllNotificationsReadAction, markNotificationReadAction } from "@/app/(dashboard)/actions";

type Notification = { id: string; title: string; body: string; type: string; is_read: boolean; created_at: string; related_type?: string | null; related_id?: string | null };
const iconFor = (type: string) => type.includes("approved") ? CheckCircle : type.includes("exception") || type.includes("overdue") ? AlertTriangle : type.includes("quote") ? FileText : Bell;
const hrefFor = (item: Notification) => item.related_type === "quote" ? `/quotes/${item.related_id}` : item.related_type === "purchase_order" ? `/pos/${item.related_id}` : item.related_type === "project" ? `/projects/${item.related_id}` : item.related_type === "invoice" ? `/invoices/${item.related_id}` : undefined;
export default function NotificationsClient({ items = [], demo = false }: { items?: Notification[]; demo?: boolean }) { const [data, setData] = useState(items); const unread = data.filter((n) => !n.is_read).length; async function read(id: string) { const form = new FormData(); form.set("notificationId", id); await markNotificationReadAction(form); setData((current) => current.map((n) => n.id === id ? { ...n, is_read: true } : n)); } async function readAll() { await markAllNotificationsReadAction(); setData((current) => current.map((n) => ({ ...n, is_read: true }))); } return <div className="p-4 md:p-8 max-w-2xl mx-auto"><PageHeader title="Notifications" subtitle={unread ? `${unread} unread` : "All caught up"} action={unread ? <button onClick={readAll} className="inline-flex items-center gap-1.5 text-sm text-brand-600"><Check className="w-4 h-4" />Mark all read</button> : undefined} />{demo && <div className="mb-4 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-800">Demo mode: notifications will appear here from real activity.</div>}<div className="divide-y divide-slate-50 rounded-xl border border-slate-200 bg-white">{data.map((item) => { const Icon = iconFor(item.type); const href = hrefFor(item); const content = <div className={`flex items-start gap-3 px-4 py-3.5 ${!item.is_read ? "bg-brand-50/40" : ""}`}><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-brand-50 text-brand-600"><Icon className="w-4 h-4" /></div><div className="min-w-0 flex-1"><p className="text-sm font-medium">{item.title}{!item.is_read && <span className="ml-2 inline-block h-2 w-2 rounded-full bg-brand-500" />}</p><p className="mt-0.5 text-xs text-slate-500">{item.body}</p><p className="mt-1 text-[11px] text-slate-400">{new Date(item.created_at).toLocaleString()}</p></div>{!item.is_read && <button onClick={() => read(item.id)} className="text-xs text-brand-600">Read</button>}</div>; return href ? <Link key={item.id} href={href}>{content}</Link> : <div key={item.id}>{content}</div>; })}{data.length === 0 && <p className="p-12 text-center text-sm text-slate-400">No notifications yet.</p>}</div></div>; }
