"use client";

import { useState } from "react";
import { UploadCloud, FileText, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { uploadDocumentAction } from "@/app/(dashboard)/actions";

export default function FilesPage() {
  const [file, setFile] = useState<File | null>(null); const [type, setType] = useState("company"); const [relatedId, setRelatedId] = useState(""); const [status, setStatus] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function upload() { if (!file) return; setBusy(true); setStatus(null); const form = new FormData(); form.set("file", file); form.set("relatedType", type); form.set("relatedId", relatedId); const result = await uploadDocumentAction(form); setStatus(result.error || `Uploaded: ${result.name}`); setBusy(false); }
  return <div className="p-4 md:p-8 max-w-2xl mx-auto"><div className="mb-6"><h1 className="text-xl font-bold">Files & photos</h1><p className="text-sm text-slate-500">Receipts, plans, PDFs, job photos and company files</p></div><div className="rounded-xl border border-slate-200 bg-white p-5 space-y-4"><label className="block cursor-pointer rounded-xl border-2 border-dashed border-slate-300 p-8 text-center hover:border-brand-400"><UploadCloud className="mx-auto mb-2 h-9 w-9 text-brand-600" /><p className="text-sm font-medium">Choose file</p><p className="mt-1 text-xs text-slate-400">PDF, JPG, PNG or WebP · max 10 MB</p><input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" className="hidden" onChange={(e) => setFile(e.target.files?.[0] || null)} /></label>{file && <p className="text-sm text-slate-600">Selected: <strong>{file.name}</strong></p>}<select value={type} onChange={(e) => setType(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="company">Company</option><option value="client">Client</option><option value="project">Project / Job</option><option value="quote">Quote</option><option value="purchase_order">Purchase Order</option><option value="expense">Expense receipt</option></select><input value={relatedId} onChange={(e) => setRelatedId(e.target.value)} placeholder="Related record ID (optional)" className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /><Button type="button" disabled={!file || busy} loading={busy} onClick={upload} className="w-full">Upload securely</Button>{status && <p className={`text-sm ${status.startsWith("Uploaded") ? "text-green-600" : "text-red-600"}`}>{status}</p>}</div><div className="mt-4 flex gap-2 rounded-xl border border-green-100 bg-green-50 p-4 text-sm text-green-800"><ShieldCheck className="h-5 w-5 shrink-0" /><span>Files are stored in the company workspace with Supabase Storage security policies.</span></div><div className="mt-6 rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Client signature</h2><p className="mt-1 text-sm text-slate-500">Signature requests will be enabled when the quote approval workflow is connected.</p><Button variant="outline" disabled className="mt-4">Request signature</Button></div></div>;
}
