"use client";

import Link from "next/link";
import { ArrowLeft, Check, Download, X } from "lucide-react";
import { useState } from "react";
import { QuoteStatusBadge } from "@/components/shared/StatusBadge";
import { Button } from "@/components/ui/Button";
import { formatCurrency } from "@/lib/utils";
import { updateQuoteStatusAction } from "@/app/(dashboard)/actions";

type Quote = { id: string; number: string; status: string; issue_date?: string; valid_until?: string | null; subtotal: number; tax_amount?: number; discount_amount?: number; total: number; terms?: string | null; notes?: string | null; client?: { name?: string } | null; project?: { name?: string } | null; items?: { id: string; description: string; quantity: number; unit_price: number; amount: number; part_number?: string | null }[] };
export default function QuoteDetailClient({ quote, demo = false }: { quote?: Quote | null; demo?: boolean }) {
  const [busy, setBusy] = useState(false);
  const q = quote ?? { id: "demo", number: "QT-DEMO", status: "draft", subtotal: 0, total: 0, client: { name: "Example client" }, items: [] };
  async function setStatus(status: string) { setBusy(true); const form = new FormData(); form.set("quoteId", q.id); form.set("status", status); await updateQuoteStatusAction(form); setBusy(false); window.location.reload(); }
  return <div className="p-4 md:p-8 max-w-2xl mx-auto"><div className="flex items-center gap-3 mb-6"><Link href="/quotes" className="w-9 h-9 rounded-full bg-slate-100 flex items-center justify-center"><ArrowLeft className="w-4 h-4" /></Link><div className="flex-1"><p className="text-xs text-slate-400">{q.number}</p><h1 className="text-lg font-bold">{q.project?.name || q.client?.name || "Quote"}</h1></div><QuoteStatusBadge status={q.status} /></div>{demo && <div className="mb-4 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-800">Demo mode: conecta Supabase para ver quotes reales.</div>}<div className="mb-4 rounded-xl border border-slate-200 bg-white p-5 space-y-2 text-sm"><div className="flex justify-between"><span className="text-slate-500">Client</span><strong>{q.client?.name || "—"}</strong></div><div className="flex justify-between"><span className="text-slate-500">Issue date</span><span>{q.issue_date || "—"}</span></div><div className="flex justify-between"><span className="text-slate-500">Valid until</span><span>{q.valid_until || "—"}</span></div></div><div className="mb-4 rounded-xl border border-slate-200 bg-white p-5"><h2 className="mb-3 font-semibold">Line items</h2><div className="space-y-3">{(q.items || []).map((item) => <div key={item.id} className="flex justify-between gap-3 border-b border-slate-50 pb-3 text-sm"><div><p className="font-medium">{item.description}</p><p className="text-xs text-slate-500">{item.part_number || ""} · {item.quantity} × {formatCurrency(Number(item.unit_price))}</p></div><strong>{formatCurrency(Number(item.amount))}</strong></div>)}</div><div className="mt-4 border-t border-slate-100 pt-3 space-y-1 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{formatCurrency(Number(q.subtotal))}</span></div><div className="flex justify-between"><span>Tax</span><span>{formatCurrency(Number(q.tax_amount || 0))}</span></div><div className="flex justify-between font-bold text-lg"><span>Total</span><span>{formatCurrency(Number(q.total))}</span></div></div></div>{(q.notes || q.terms) && <div className="mb-4 rounded-xl border border-slate-200 bg-white p-5 text-sm"><p>{q.notes}</p><p className="mt-3 text-slate-500">{q.terms}</p></div>}<div className="flex flex-wrap gap-2"><a href={`/api/quotes/${q.id}/pdf`} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm"><Download className="w-4 h-4" />PDF</a>{q.status === "draft" || q.status === "rejected" ? <Button disabled={busy || demo} onClick={() => setStatus("sent")}><Check className="w-4 h-4" />Send</Button> : null}{q.status === "sent" ? <><Button disabled={busy || demo} onClick={() => setStatus("approved")}><Check className="w-4 h-4" />Approve</Button><Button disabled={busy || demo} variant="danger" onClick={() => setStatus("rejected")}><X className="w-4 h-4" />Reject</Button></> : null}</div></div>;
}
