"use client";

import { useMemo } from "react";
import { BarChart3, Download, FileText, Receipt, TrendingUp, Briefcase } from "lucide-react";
import { PageHeader } from "@/components/shared/PageHeader";
import { Button } from "@/components/ui/Button";
import { formatCurrency } from "@/lib/utils";
import { useI18n } from "@/lib/i18n/provider";

type Data = { metrics?: { totalContractValue: number; totalProfit: number; pendingQuotes: number; pendingInvoices: number; expensesThisMonth: number }; projects?: { status: string; name: string; contract_value: number; spentTotal: number }[]; quotes?: { status: string; total: number }[]; invoices?: { status: string; total: number; amount_paid: number }[]; expenses?: { amount: number; vendor_name?: string | null; category?: { name?: string } | null }[] };
export default function ReportsClient({ metrics, projects = [], quotes = [], invoices = [], expenses = [], demo = false }: Data & { demo?: boolean }) { const { t } = useI18n(); const m = metrics || { totalContractValue: 0, totalProfit: 0, pendingQuotes: 0, pendingInvoices: 0, expensesThisMonth: 0 }; const totalExpenses = expenses.reduce((sum, e) => sum + Number(e.amount), 0); const totalSales = quotes.filter((q) => q.status === "approved").reduce((sum, q) => sum + Number(q.total), 0); const overdue = invoices.filter((i) => i.status === "overdue").reduce((sum, i) => sum + Math.max(0, Number(i.total) - Number(i.amount_paid)), 0); const jobs = useMemo(() => projects.reduce<Record<string, number>>((acc, p) => { acc[p.status] = (acc[p.status] || 0) + 1; return acc; }, {}), [projects]); function exportCsv() { const rows = [["Report", "Value"], ["Contracted sales", m.totalContractValue], ["Approved quotes", totalSales], ["Expenses", totalExpenses], ["Estimated profit", m.totalProfit], ["Pending invoices", m.pendingInvoices], ["Overdue invoices", overdue], ...Object.entries(jobs).map(([status, count]) => [`Jobs ${status}`, count])]; const blob = new Blob([rows.map((row) => row.join(",")).join("\n")], { type: "text/csv" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "contractoros-report.csv"; a.click(); URL.revokeObjectURL(url); }
  const cards = [{ label: "Contracted sales", value: formatCurrency(m.totalContractValue), icon: TrendingUp }, { label: "Approved quotes", value: formatCurrency(totalSales), icon: FileText }, { label: "Expenses", value: formatCurrency(totalExpenses), icon: Receipt }, { label: "Estimated profit", value: formatCurrency(m.totalProfit), icon: BarChart3 }, { label: "Pending invoices", value: String(m.pendingInvoices), icon: FileText }, { label: "Overdue invoices", value: formatCurrency(overdue), icon: Receipt }]; return <div className="p-4 md:p-8"><PageHeader title={t("reports")} action={<Button variant="outline" size="sm" onClick={exportCsv}><Download className="w-4 h-4" />{t("exportReports")}</Button>} />{demo && <div className="mb-5 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-800">{t("demoMode")}: configura Supabase para reportes reales.</div>}<div className="grid grid-cols-2 md:grid-cols-3 gap-3 mb-6">{cards.map((card) => <div key={card.label} className="rounded-xl border border-slate-200 bg-white p-4"><card.icon className="mb-2 h-4 w-4 text-brand-600" /><p className="text-xs text-slate-500">{card.label}</p><p className="mt-1 text-xl font-bold">{card.value}</p></div>)}</div><div className="grid md:grid-cols-2 gap-4"><div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="mb-4 flex items-center gap-2 font-semibold"><Briefcase className="h-4 w-4" />Jobs by status</h2>{Object.keys(jobs).length === 0 ? <p className="text-sm text-slate-400">No jobs yet.</p> : Object.entries(jobs).map(([status, count]) => <div key={status} className="flex justify-between border-b border-slate-50 py-2 text-sm"><span className="capitalize">{status.replace("_", " ")}</span><strong>{count}</strong></div>)}</div><div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="mb-4 font-semibold">Quote conversion</h2><div className="space-y-2 text-sm"><div className="flex justify-between"><span>Total quotes</span><strong>{quotes.length}</strong></div><div className="flex justify-between"><span>Approved</span><strong>{quotes.filter((q) => q.status === "approved").length}</strong></div><div className="flex justify-between"><span>Pending</span><strong>{m.pendingQuotes}</strong></div></div></div></div></div>; }
