"use client";

import { ArrowLeft, Plus, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Button } from "@/components/ui/Button";

type Material = { id: string; description: string; partNumber: string; quantity: number; unit: string; notes: string };
const emptyMaterial = (): Material => ({ id: crypto.randomUUID(), description: "", partNumber: "", quantity: 1, unit: "each", notes: "" });

export default function MaterialListPage() {
  const router = useRouter();
  const [materials, setMaterials] = useState<Material[]>([emptyMaterial()]);
  const [saved, setSaved] = useState(false);
  function update(id: string, field: keyof Material, value: string | number) { setMaterials((items) => items.map((item) => item.id === id ? { ...item, [field]: value } : item)); setSaved(false); }
  function add() { setMaterials((items) => [...items, emptyMaterial()]); setSaved(false); }
  function remove(id: string) { if (materials.length > 1) setMaterials((items) => items.filter((item) => item.id !== id)); }
  function save() { const valid = materials.filter((item) => item.description.trim()); localStorage.setItem("contractoros:material-list", JSON.stringify(valid)); setSaved(true); }
  return <div className="p-4 md:p-8 max-w-3xl mx-auto"><button onClick={() => router.back()} className="mb-6 flex items-center gap-2 text-sm text-slate-500"><ArrowLeft className="h-4 w-4" />Back</button><div className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-brand-600">Supply & Purchase</p><h1 className="mt-1 text-2xl font-bold">Material list</h1><p className="mt-2 text-sm text-slate-500">Prepare the materials first. You can send this list later as a supply quote request.</p></div><div className="surface-card p-4 md:p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">Materials</h2><p className="text-xs text-slate-500">Add as many items as needed.</p></div><button type="button" onClick={add} className="inline-flex items-center gap-1 text-sm font-semibold text-brand-600"><Plus className="h-4 w-4" />Add item</button></div><div className="space-y-4">{materials.map((item, index) => <div key={item.id} className="rounded-xl border border-slate-200 p-3"><div className="mb-3 flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-wide text-slate-400">Item {index + 1}</span><button type="button" onClick={() => remove(item.id)} disabled={materials.length === 1} className="p-1 text-slate-400 hover:text-red-500 disabled:opacity-30" aria-label="Remove item"><Trash2 className="h-4 w-4" /></button></div><div className="grid gap-3 sm:grid-cols-2"><input required value={item.description} onChange={(e) => update(item.id, "description", e.target.value)} placeholder="Description, e.g. 10 AWG black THHN" className="rounded-lg border border-slate-200 px-3 py-2.5 text-sm sm:col-span-2" /><input value={item.partNumber} onChange={(e) => update(item.id, "partNumber", e.target.value)} placeholder="Part number (optional)" className="rounded-lg border border-slate-200 px-3 py-2.5 text-sm" /><div className="grid grid-cols-2 gap-2"><input type="number" min="0.01" step="0.01" value={item.quantity} onChange={(e) => update(item.id, "quantity", Number(e.target.value) || 0)} className="rounded-lg border border-slate-200 px-3 py-2.5 text-sm" /><select value={item.unit} onChange={(e) => update(item.id, "unit", e.target.value)} className="rounded-lg border border-slate-200 px-2 py-2.5 text-sm"><option>each</option><option>ft</option><option>box</option><option>roll</option><option>lot</option></select></div><input value={item.notes} onChange={(e) => update(item.id, "notes", e.target.value)} placeholder="Notes (optional)" className="rounded-lg border border-slate-200 px-3 py-2.5 text-sm sm:col-span-2" /></div></div>)}</div><div className="mt-5 flex flex-col gap-3 sm:flex-row sm:justify-end"><Button type="button" variant="outline" onClick={save}>Save material list</Button><Button type="button" onClick={() => router.push("/supply-requests")}>Create supply request</Button></div>{saved && <p className="mt-3 text-sm text-green-700">Material list saved on this device.</p>}</div></div>;
}
